### ISSUE TITLE
Can't auth with github (firefox)

### ISSUE THREAD

**Issue by RedstoneMedia** [benawad/vsinder#99]
## I can't authenticate with GitHub using Firefox on windows 10.
 
I get this error in the developer console in vs code :
```js
listen EACCES: permission denied 0.0.0.0:54321: Error: listen EACCES: permission denied 0.0.0.0:54321
    at Server.setupListenHandle [as _listen2] (net.js:1289:21)
    at listenInCluster (net.js:1354:12)
    at Server.listen (net.js:1442:7)
    at d.listen (c:\Users\NotMyName\.vscode\extensions\benawad.vsinder-1.14.0\dist\extension.js:1:20544)
    at Object.t.authenticate (c:\Users\NotMyName\.vscode\extensions\benawad.vsinder-1.14.0\dist\extension.js:1:38805)
    at t.SidebarProvider.<anonymous> (c:\Users\NotMyName\.vscode\extensions\benawad.vsinder-1.14.0\dist\extension.js:1:25546)
    at Generator.next (<anonymous>)
    at c:\Users\NotMyName\.vscode\extensions\benawad.vsinder-1.14.0\dist\extension.js:1:23772
    at new Promise (<anonymous>)
    at s (c:\Users\NotMyName\.vscode\extensions\benawad.vsinder-1.14.0\dist\extension.js:1:23517)
    at c:\Users\NotMyName\.vscode\extensions\benawad.vsinder-1.14.0\dist\extension.js:1:24222
    at l.fire (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:46:67)
    at t.ExtHostWebviews.$onMessage (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:847:889)
    at g._doInvokeHandler (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:876:926)
    at g._invokeHandler (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:876:618)
    at g._receiveRequest (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:875:252)
    at g._receiveOneMessage (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:874:6)
    at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:872:136
    at l.fire (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:46:67)
    at v.fire (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:256:601)
    at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:1066:179
    at l.fire (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:46:67)
    at v.fire (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:256:601)
    at t.PersistentProtocol._receiveMessage (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:261:629)
    at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:258:708
    at l.fire (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:46:67)
    at p.acceptChunk (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:253:989)
    at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:253:341
    at Socket.t (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:263:276)
    at Socket.emit (events.js:223:5)
    at addChunk (_stream_readable.js:309:12)
    at readableAddChunk (_stream_readable.js:290:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:181:23)
```

This is what Firefox shows me :
![Screenshot 2020-12-13 164635](https://user-images.githubusercontent.com/34373974/102016776-dc79ef00-3d62-11eb-9442-04de55481c82.png)

**Comment by benawad** [comment]
Is there a reason vscode wouldn't have access to start a server on port 54321 (it's needed for auth)?

**Comment by RedstoneMedia** [comment]
I have no idea. I did `netstat -a` and nothing is appearing to be listening on port 5432.

**Comment by benawad** [comment]
maybe https://superuser.com/a/1568476

I don't think there's anything I can do on my end, looks like a permission thing you need to configure. A quick fix might be to try running vscode as administrator
